version: "3"

services:
  nextjs-container:
    build:
      context: ./website
      dockerfile: Dockerfile.website
    ports:
      - "3000:3000"

  nginx-container:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - nextjs-container
