version: "3"

services:
  express-server-container:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  nextjs-container:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - express-server-container

  nginx-container:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - nextjs-container
      - express-container
